DROP DATABASE IF EXISTS STOCKS;
CREATE DATABASE STOCKS;
USE STOCKS;

DROP TABLE IF EXISTS Prediction;
CREATE TABLE Prediction (
P_ID VARCHAR(4) NOT NULL,
PRIMARY KEY(P_ID)
);

DROP TABLE IF EXISTS Business;
CREATE TABLE Business (
BusinessID VARCHAR(4) NOT NULL,
Address VARCHAR(45) NOT NULL, 
FoundingDate DATE NOT NULL,
CompanyName VARCHAR(25) NOT NULL,
PRIMARY KEY(BusinessID)
);

DROP TABLE IF EXISTS User;
CREATE TABLE User (
Username VARCHAR(16) NOT NULL,
Password VARCHAR(25) NOT NULL,
Permissions VARCHAR(16) NOT NULL, 
PRIMARY KEY(Username)
);

DROP TABLE IF EXISTS Exchanges;
CREATE TABLE Exchanges (
Name VARCHAR(25) NOT NULL,
Location VARCHAR(25) NOT NULL, 
NumberOfTickers INT NOT NULL, 
PRIMARY KEY(Name)
);

DROP TABLE IF EXISTS BelongsTo;
CREATE TABLE BelongsTo (
ID VARCHAR(4) NOT NULL,
Name VARCHAR(25) NOT NULL,
PRIMARY KEY(ID),
CONSTRAINT Name FOREIGN KEY (Name) REFERENCES Exchanges(Name)
);

DROP TABLE IF EXISTS Stock;
CREATE TABLE Stock(
BusinessID VARCHAR(4) NOT NULL,
PredictionID VARCHAR(4) NOT NULL,
ID VARCHAR(4) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT BusinessID FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID),
CONSTRAINT PredictionID FOREIGN KEY (PredictionID) REFERENCES Prediction(P_ID),
CONSTRAINT ID FOREIGN KEY (ID) REFERENCES BelongsTo(ID)
);

DROP TABLE IF EXISTS Analyst;
CREATE TABLE Analyst (
AnalystID_Number VARCHAR(4) NOT NULL,
ID VARCHAR(4) NOT NULL,
Name VARCHAR(25) NOT NULL,
Company VARCHAR(25) NOT NULL,
PRIMARY KEY(AnalystID_Number),
CONSTRAINT ID1 FOREIGN KEY (ID) REFERENCES Stock(ID)
);

DROP TABLE IF EXISTS Admin;
CREATE TABLE Admin (
Username VARCHAR(16) NOT NULL,
PRIMARY KEY(Username),
CONSTRAINT Username1 FOREIGN KEY (Username) REFERENCES User(Username)
);

DROP TABLE IF EXISTS Watchlist;
CREATE TABLE Watchlist (
ID VARCHAR(4) NOT NULL,
ListNumber INT NOT NULL,
Ranking VARCHAR(25) NOT NULL,
PRIMARY KEY(ListNumber),
CONSTRAINT ID2 FOREIGN KEY (ID) REFERENCES Stock(ID)
);

DROP TABLE IF EXISTS Private;
CREATE TABLE Private (
Username VARCHAR(16) NOT NULL,
ListNumber INT NOT NULL, 
PRIMARY KEY(Username),
CONSTRAINT Username2 FOREIGN KEY (Username) REFERENCES User(Username),
CONSTRAINT ListNumber FOREIGN KEY (ListNumber) REFERENCES Watchlist(ListNumber)
);

DROP TABLE IF EXISTS BusinessUser;
CREATE TABLE BusinessUser (
Username VARCHAR(16) NOT NULL,
ListNumber INT NOT NULL, 
PRIMARY KEY(Username),
CONSTRAINT Username3 FOREIGN KEY (Username) REFERENCES User(Username),
CONSTRAINT ListNumber1 FOREIGN KEY (ListNumber) REFERENCES Watchlist(ListNumber)
);

DROP TABLE IF EXISTS StockEvent;
CREATE TABLE StockEvent (
EventID VARCHAR(4) NOT NULL,
StockID VARCHAR(4) NOT NULL, 
PRIMARY KEY(EventID),
CONSTRAINT Username3 FOREIGN KEY (Username) REFERENCES User(Username),
CONSTRAINT ListNumber1 FOREIGN KEY (ListNumber) REFERENCES Watchlist(ListNumber)
);
