DROP DATABASE IF EXISTS STOCKS;
CREATE DATABASE STOCKS;
USE STOCKS;

CREATE TABLE STOCK (
BusinessID VARCHAR(4) NOT NULL,
PredictionID VARCHAR(4) NOT NULL,
ID VARCHAR(4) NOT NULL,
FOREIGN KEY (BusinessID) REFERENCES BUSINESS(BusinessID),
FOREIGN KEY (PredictionID) REFERENCES PREDICTION(P_ID),
PRIMARY KEY (ID)
);

CREATE TABLE PREDICTION (
PRIMARY KEY(P_ID)
);

CREATE TABLE BUSINESS (
PRIMARY KEY(BusinessID)
);